# Google Cloud Build configuration for Settlers of Stock
steps:
  # Step 1: Install backend dependencies and run tests
  - name: 'python:3.11-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend
        pip install uv
        uv pip install --system -r requirements.txt
        python -m pytest tests/ -v --tb=short
    id: 'backend-test'

  # Step 2: Build and test frontend
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd frontend
        npm ci
        npm run test:ci
        npm run build
    id: 'frontend-build'
    waitFor: ['-']

  # Step 3: Build backend Docker image for Cloud Run (alternative deployment)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/settlers-of-stock-backend:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/settlers-of-stock-backend:latest'
      - './backend'
    id: 'backend-docker-build'
    waitFor: ['backend-test']

  # Step 4: Build frontend Docker image for Cloud Run
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/settlers-of-stock-frontend:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/settlers-of-stock-frontend:latest'
      - './frontend'
    id: 'frontend-docker-build'
    waitFor: ['frontend-build']

  # Step 5: Push Docker images to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/settlers-of-stock-backend:$BUILD_ID']
    id: 'backend-docker-push'
    waitFor: ['backend-docker-build']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/settlers-of-stock-backend:latest']
    waitFor: ['backend-docker-push']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/settlers-of-stock-frontend:$BUILD_ID']
    id: 'frontend-docker-push'
    waitFor: ['frontend-docker-build']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/settlers-of-stock-frontend:latest']
    waitFor: ['frontend-docker-push']

  # Step 6: Deploy to App Engine (primary deployment method)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'app'
      - 'deploy'
      - 'app.yaml'
      - '--quiet'
      - '--promote'
    dir: 'backend'
    id: 'app-engine-deploy'
    waitFor: ['backend-test']

  # Step 7: Deploy frontend to Cloud Storage (static hosting)
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '-d'
      - './frontend/build/'
      - 'gs://$PROJECT_ID-frontend/'
    id: 'frontend-deploy'
    waitFor: ['frontend-build']

  # Step 8: Set proper cache headers for static assets
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'setmeta'
      - '-h'
      - 'Cache-Control:public, max-age=31536000'
      - 'gs://$PROJECT_ID-frontend/static/**'
    waitFor: ['frontend-deploy']

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'

# Build timeout
timeout: '1200s'

# Substitutions for environment-specific values
substitutions:
  _ENVIRONMENT: 'production'
  _GCP_REGION: 'us-central1'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/settlers-of-stock-backend:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/settlers-of-stock-backend:latest'
  - 'gcr.io/$PROJECT_ID/settlers-of-stock-frontend:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/settlers-of-stock-frontend:latest'