# Google App Engine configuration for Settlers of Stock
runtime: python311
service: default
entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

# Instance configuration
instance_class: F2
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Environment variables (secrets will be managed separately)
env_variables:
  ENVIRONMENT: production
  DEBUG: false
  GCP_PROJECT_ID: settlers-of-stock-prod
  GCP_REGION: us-central1
  VERTEX_AI_LOCATION: us-central1
  VERTEX_AI_MODEL: gemini-1.5-flash
  LOG_LEVEL: INFO
  PORT: 8080
  
# Health check configuration
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# Network configuration
network:
  forwarded_ports:
    - 8000

# Skip files for deployment
skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^(.*/)?tests/.*$
  - ^(.*/)?test_.*\.py$
  - ^(.*/)?.*_test\.py$
  - ^(.*/)?pytest\.ini$
  - ^(.*/)?\.pytest_cache/.*$
  - ^(.*/)?__pycache__/.*$
  - ^(.*/)?\.coverage$
  - ^(.*/)?\.env\..*$
  - ^(.*/)?node_modules/.*$
  - ^(.*/)?frontend/.*$
  - ^(.*/)?\.git/.*$
  - ^(.*/)?\.github/.*$
  - ^(.*/)?\.vscode/.*$
  - ^(.*/)?\.kiro/.*$
  - ^(.*/)?docker-compose\.yml$
  - ^(.*/)?Dockerfile$
  - ^(.*/)?\.dockerignore$
  - ^(.*/)?setup\.sh$
  - ^(.*/)?dev\.sh$
  - ^(.*/)?README\.md$
  - ^(.*/)?.*\.md$

# Handlers for static files and API
handlers:
  # API routes
  - url: /api/.*
    script: auto
    secure: always
    
  # Health check endpoints
  - url: /health
    script: auto
    secure: always
    
  - url: /status
    script: auto
    secure: always
    
  # Root endpoint
  - url: /
    script: auto
    secure: always
    
  # Catch all other routes
  - url: /.*
    script: auto
    secure: always